name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
    paths:
      - "mock-growatt/**"
      - ".github/workflows/mock-growatt-lint.yml"
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: mock-growatt
